language: php

os: 
- linux
- windows

env:
  global:
    - HTTP_HOST=dframeframework.com
    - MOD_REWRITE=true

php:
  - 7.0
  - 7.1
  - 7.2

# We don't want to run linux commands as super user
sudo: false

install: 
   composer install

script:
   - phpunit
