name: CI

on: [push]

jobs:
  build-test:
    runs-on: debian-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: Scarlett
        with:
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
          php_version: "8.1"